[project]
name = "Peng-Agent"
version = "1.0.0"
description = "A LLM ongoing chat agent for learning"
authors = [{ name = "Noah Ding", email = "noah@dingyipeng.com" }]
dependencies = [
    "bs4>=0.0.2",
    "fastapi>=0.115.11",
    "langchain>=0.3.20",
    "langchain-community>=0.3.19",
    "langchain-core>=0.3.45",
    "langchain-ollama>=0.2.3",
    "langchain-qdrant>=0.2.0",
    "minio>=7.2.15",
    "mysql-connector-python>=9.2.0",
    "ollama>=0.4.7",
    "openai>=1.66.3",
    "pdf2image>=1.17.0",
    "pydantic>=2.10.6",
    "pypdf>=5.3.1",
    "python-dotenv>=1.0.1",
    "qdrant-client>=1.13.3",
    "requests>=2.32.3",
    "uvicorn>=0.34.0",
]
requires-python = ">=3.11"
